configuration: Release

image: Visual Studio 2017

branches:
  only:
    - master

before_build:
- ps: nuget restore

build:
  verbosity: minimal

deploy:
  tag: LatestCommit
  release: StudioSB [Latest Commit]
  description: 'This build is updated every time a commit is pushed to the master branch.\n\nMessage: $(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  auth_token: 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
  artifact: StudioSB.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master

after_build:
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\StudioSB.exe"
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\StudioSB.exe.config"
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\OpenTK.dll"
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\OpenTK.GLControl.dll"
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\lib"
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\DefaultTextures"
  - 7z a "StudioSB.zip" "%APPVEYOR_BUILD_FOLDER%\StudioSB\bin\Release\Shaders"
  - appveyor PushArtifact "StudioSB.zip"
